/*
 * Copyright 2009-2011 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an
 * "AS IS" BASIS,  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language
 * governing permissions and limitations under the License.
 */

package org.powertac.common

/**
 * A broker domain instance represents a competition participants, or more
 * precisely the competition participant's agent. Every incoming request
 * from a broker agent is authenticated against the credentials stored in this class.
 * Broker instances are not communicated to other brokers; only usernames are 
 * considered public information and get communicated.
 *
 * @author Carsten Block, David Dauer
 * @version 1.1 , 03/22/2011
 */
class Broker {

  String id = IdGenerator.createId()

  /** the broker's login or user name     */
  String username
  /* Spring Security-related generated fields */
  String password
  Boolean enabled
  Boolean accountExpired
  Boolean accountLocked
  Boolean passwordExpired

  /** If true, the broker is local to the server and does not receive messages  */
  Boolean local = false
  
  /** If true, broker is a wholesale market participant, but not a "real" broker */
  Boolean wholesale = false

  def testProxy = null // redirect incoming messages for testing

  /** Broker's current cash position  */
  CashPosition cashPosn

  static auditable = true

  static hasOne = [cashPosn:CashPosition]

  static hasMany = [shouts: Shout, tariffs: Tariff, marketPositions: MarketPosition]
  static transients = ['cash', 'apiKey', 'testProxy']
  static constraints = {
    id(nullable: false, blank: false, unique: true)
    username(nullable: false, blank: false, unique: true, minSize: 2, matches: /([a-zA-Z0-9_])*/)
    password(nullable: true, blank: false, minSize: 2) // TODO: with nullable:false all tests fail?!
    //apiKey(nullable: false, blank: false, unique: true, minSize: 32)
    cashPosn(nullable: true)
    enabled(nullable: true)
    accountExpired(nullable: true)
    accountLocked(nullable: true)
    passwordExpired(nullable: true)
    //shouts(nullable: true)
    //tariffs(nullable: true)
    //marketPositions(nullable: true)
  }

  static mapping = {
    cache(true)
    id(generator: 'assigned')
    username(index: 'username_idx')
    //apiKey(index: 'username_apikey_idx')
    password(column: 'password_col') // Generated by Spring Security
  }

  String getApiKey() {
    return id
  }

  CashPosition getCash() {
    if (cashPosn == null) {
      cashPosn = new CashPosition(broker: this, balance: 0.0)
      //cashPosn.save()
    }
    return cashPosn
  }

  void setCash(CashPosition thing) {
    cashPosn = thing
  }

  // Generated by Spring Security

  Set<Role> getAuthorities() {
    BrokerRole.findAllByBroker(this).collect { it.role } as Set
  }

  public String toString() {
    return username
  }

  public String toQueueName() {
    return "brokers.${this.username}.outputQueue";
  }

  /**
   * default implementation does nothing.
   * brokers shipping within the server can overwrite this method to receive messages from BrokerProxy
   * @param object the message object received from BrokerProxy
   */
  void receiveMessage(Object object) {
    if (!local) {
      log.error "receiveMessage() should only be called for local brokers"
    }
    testProxy?.receive(object)
  }
}
